/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MesReservationsRouteImport } from './routes/mes-reservations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVehiculesRouteImport } from './routes/admin.vehicules'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminRapportsRouteImport } from './routes/admin.rapports'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MesReservationsRoute = MesReservationsRouteImport.update({
  id: '/mes-reservations',
  path: '/mes-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculesRoute = AdminVehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRapportsRoute = AdminRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/profil': typeof ProfilRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/profil': typeof ProfilRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/profil': typeof ProfilRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/mes-reservations'
    | '/profil'
    | '/admin/clients'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/vehicules'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/mes-reservations'
    | '/profil'
    | '/admin/clients'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/vehicules'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/mes-reservations'
    | '/profil'
    | '/admin/clients'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/vehicules'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  MesReservationsRoute: typeof MesReservationsRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-reservations': {
      id: '/mes-reservations'
      path: '/mes-reservations'
      fullPath: '/mes-reservations'
      preLoaderRoute: typeof MesReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicules': {
      id: '/admin/vehicules'
      path: '/vehicules'
      fullPath: '/admin/vehicules'
      preLoaderRoute: typeof AdminVehiculesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapports': {
      id: '/admin/rapports'
      path: '/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AdminRapportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminRapportsRoute: typeof AdminRapportsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminVehiculesRoute: typeof AdminVehiculesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminRapportsRoute: AdminRapportsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminVehiculesRoute: AdminVehiculesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  MesReservationsRoute: MesReservationsRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
